image: debian/testing
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
packages:
  - hut
  - emacs-nox
  - elpa-htmlize
sources:
  - https://git.sr.ht/~taingram/emacs-init
environment:
  README: init.org
tasks:
  - export-readme: |
      cd emacs-init
      emacs --daemon
      emacsclient -e \
      "(setq vc-handled-backends nil)
       (setq org-startup-folded nil)
       (setq org-element-cache-persistent nil)
       (setq org-html-htmlize-output-type 'inline-css)
       (load-theme 'modus-operandi)
       (with-temp-buffer
         (find-file \"$README\")
         (org-html-export-to-html nil nil nil t)))"
      hut git update --readme $(basename "$README" .org).html
